# Machine Learning: Week 5 - Neural Networks: Learning
## Cost Function
Let's first define a few variables that we will need to use:
- $L =$ total number of layers in the network
- $s_l =$ number of units (not counting bias unit) in layer $l$
- $K =$ number of output units/classes

Recall that in neural networks, we may have many output nodes. We denote $h_\Theta(x)_k$ as being a hypothesis that results in the $k^{th}$ output. Our cost function for neural networks is going to be a generalization of the one we used for logistic regression. Recall that the cost function for regularized logistic regression was:

$$\large
J( \theta ) =-\frac{1}{m}\sum _{i=1}^{m}\left[ y^{( i)} log\left( h_{\theta }\left( x^{( i)}\right)\right) +\left( 1-y^{( i)}\right) log\left( 1-h_{\theta }\left( x^{( i)}\right)\right)\right] +\frac{\lambda }{2m}\sum _{j=1}^{n} \theta _{j}^{2}
$$

For neural networks, it is going to be slightly more complicated:

$$\large
J( \Theta ) =-\frac{1}{m}\sum _{i=1}^{m}\sum _{k=1}^{K}\left[ y_{k}^{( i)} log\left(\left( h_{\theta }\left( x^{( i)}\right)\right)_{k}\right) +\left( 1-y_{k}^{( i)}\right) log\left( 1-\left( h_{\theta }\left( x^{( i)}\right)\right)_{k}\right)\right] +\frac{\lambda }{2m}\sum _{l=1}^{L-1}\sum _{i=1}^{s_{l}}\sum _{j=1}^{s_{l+1}}\left( \Theta _{j,i}^{l}\right)^{2}
$$

We have added a few nested summations to account for our multiple output nodes. In the first part of the equation, before the square brackets, we have an additional nested summation that loops through the number of output nodes.

In the regularization part, after the square brackets, we must account for multiple theta matrices. The number of columns in our current theta matrix is equal to the number of nodes in our current layer (including the bias unit). The number of rows in our current theta matrix is equal to the number of nodes in the next layer (excluding the bias unit). As before with logistic regression, we square every term.

Note:
- the double sum simply adds up the logistic regression costs calculated for each cell in the output layer
- the triple sum simply adds up the squares of all the individual $\Theta$s in the entire network.
- the $i$ in the triple sum does not refer to training example $i$



## Backpropagation Algorithm
“Backpropagation” is neural-network terminology for minimizing our cost function, just like what we were doing with gradient descent in logistic and linear regression.

Our goal is to compute:

$$\large
min_\Theta J(\Theta)
$$

That is, we want to minimize our cost function J using an optimal set of parameters in theta. In this section we'll look at the equations we use to compute the partial derivative of $J(\Theta($:

$$\large
\frac{\partial }{\partial \Theta _{ij}^{( l)}} J( \Theta )
$$

To do so, we use the following algorithm:

![backpropagation_algo](./Week5_Images/backpropagation_algo.png)

<br>

![gradient_computation](./Week5_Images/gradient_computation.png)

### Backpropagation Algorithm
In back propagation we’re going to compute for every node:

$$\large
\delta^{(l)}_j = error\ \ of\ \ node\ \ j\ \ in\ \ layer\ \ l
$$

Recall that $a^{(l)}_j$ is activation node $j$ in layer $l$.

For the last layer, we can compute the vector of delta values with:

$$\large
\delta^{(L)} = a^{(L)} - y^{(t)}
$$

Where L is our total number of layers and $a^{(L)}$ is the vector of outputs of the activation units for the last layer. So our “error values” for the last layer are simply the differences of our actual results in the last layer and the correct outputs in $y$.

To get the delta values of the layers before the last layer, we can use an equation that steps us back from right to left:

$$\large
g'( u) =g( u) .*( 1-g( u))
$$

The full back propagation equation for the inner nodes is then:

$$\large
\delta^{(l)} = ((\Theta^{(l)})^T \delta^{(l+1)})\ .*\ a^{(l)}\ .*\ (1 - a^{(l)})
$$

Andrew Ng states that the derivation and proofs are complicated and involved, but you can still implement the above equations to do back propagation without knowing the details.

We can compute our partial derivative terms by multiplying our activation values and our error values for each training example $t$:

$$\large
\frac{\partial J( \Theta )}{\partial \Theta _{ij}^{( l)}} =\frac{1}{m}\sum _{t=1}^{m} a_{k}^{( t)( l)} \delta ^{( t)( l-1)}
$$

Note: $\delta^{(l+1)}$ and $a^{(l+1)}$ are vectors with $s^{(l+1)}$ elements. Similarly, $(a^{(l)})$ is a vector with sl elements. Multiplying them produces a matrix that is $s^{(l+1)}$ by $s^l$ which is the same dimension as $\Theta^{(l)}$. That is, the process produces a gradient term for every element in $\Theta^{(l)}$. (Actually, $\Theta^{(l)}$ has $s^{(l + 1)}$ column, so the dimensionality is not exactly the same).

We can now take all these equations and put them together into a backpropagation algorithm:


### Backpropagation Algorithm
Given training set ${(x(1),y(1))...(x(m),y(m))}$
- Set $\Delta^{(l)}_{i,j}:=0$ for all $(l,i,j)$

For training example t =1 to m:
- Set $a^{(1)}:=x^{(t)}$

- Perform forward propagation to compute $a^{(l)}$ for $l=2,3,...,L$

- Using $y^{(t)}$, compute $\delta ^{( L)} =a^{( L)} -y^{( t)}$

- Compute $\delta ^{( L-1)} ,\delta ^{( L-2)} ,...,\delta ^{( 2)}$ using $\delta ^{( l)} =\left(\left( \Theta ^{( l)}\right)^{T} \delta ^{( l+1)}\right) .*a^{( l)} .*( 1-a)$

- $\Delta^{(l)}_{i,j}:= \Delta^{(l)}_{i,j} + a^{(l)}_j \delta^{(l+1)}_i$ or with vectorization, $\Delta^{(l)}:=\Delta^{(l)}+\delta^{(l+1)}(a^{(l)})T$

- $D_{i,j}^{( l)} :=\frac{1}{m}\left( \Delta _{i,j}^{( l)} +\lambda \Theta _{i,j}^{( l)}\right) \ \ if\ \ j\neq 0$

- $D_{i,j}^{( l)} :=\frac{1}{m} \Delta _{i,j}^{( l)} \ \ if\ \ j=0$

The capital-delta matrix is used as an “accumulator” to add up our values as we go along and eventually compute our partial derivative.

The actual proof is quite involved, but, the $\Delta^{(l)}_{i,j}$ terms are the partial derivatives and the results we are looking for:

$$\large
D_{i,j}^{( l)} =\frac{\partial J( \Theta )}{\partial \Theta _{i,j}^{( l)}}
$$


## Backpropagation Intuition
Recall that the cost function for a neural network is:

$$\large
J( \Theta ) =-\frac{1}{m}\sum _{i=1}^{m}\sum _{k=1}^{K}\left[ y_{k}^{( i)} log\left(\left( h_{\theta }\left( x^{( i)}\right)\right)_{k}\right) +\left( 1-y_{k}^{( i)}\right) log\left( 1-\left( h_{\theta }\left( x^{( i)}\right)\right)_{k}\right)\right] +\frac{\lambda }{2m}\sum _{l=1}^{L-1}\sum _{i=1}^{s_{l}}\sum _{j=1}^{s_{l+1}}\left( \Theta _{j,i}^{l}\right)^{2}
$$

If we consider simple non-multiclass classification $(k = 1)$ and disregard regularization, the cost is computed with:

$$\large
cost( t) =y^{( t)} log\left( h_{\Theta }\left( x^{( t)}\right)\right) +\left( 1-y^{( t)}\right) log\left( 1-h_{\Theta }\left( x^{( t)}\right)\right)
$$

Intuitively, $\delta_j^{(l)}$ is the "error" for $a^{(l)}_j$ (unit $j$ in layer $l$). More formally, the delta values are actually the derivative of the cost function:

$$\large
\delta _{j}^{( l)} =\frac{\partial }{\partial z_{j}^{( l)}} cost( t)
$$

Recall that our derivative is the slope of a line tangent to the cost function, so the steeper the slope the more incorrect we are. Let us consider the following neural network below and see how we could calculate some $\delta_j^{(l)}$:

![forward_propagation](./Week5_Images/forward_propagation.png)

In the image above, to calculate $\delta_2^{(2)}$, we multiply the weights $\Theta^{(2)}_{12}$ and $\Theta^{(2)}_{22}$ by their respective $\delta$ values found to the right of each edge. So we get $\delta _{2}^{( 2)} =\Theta _{12}^{( 2)} *\delta _{1}^{( 3)} +\Theta _{22}^{( 2)} *\delta _{2}^{( 3)}$. To calculate every single possible $\delta_j^{(l)}$, we could start from the right of our diagram. We can think of our edges as our $\Theta_{ij}$. Going from right to left, to calculate the value of $\delta^{(l)}_j$, you can just take the over all sum of each weight times the $\delta$ it is coming from. Hence, another example would be $\delta _{2}^{( 3)} =\Theta _{12}^{( 3)} *\delta _{1}^{( 4)}$

## Putting it Together
First, pick a network architecture; choose the layout of your neural network, including how many hidden units in each layer and how many layers total.
- Number of input units = dimension of features x(i)
- Number of output units = number of classes
- Number of hidden units per layer = usually more the better (must balance with cost of computation as it increases with more hidden units)
- Defaults: 1 hidden layer. If more than 1 hidden layer, then the same number of units in every hidden layer.

### Training a Neural Network
1. Randomly initialize the weights
2. Implement forward propagation to get hθ(x(i))
3. Implement the cost function
4. Implement backpropagation to compute partial derivatives
5. Use gradient checking to confirm that your backpropagation works. Then disable gradient checking.
6. Use gradient descent or a built-in optimization function to minimize the cost function with the weights in theta.

When we perform forward and back propagation, we loop on every training example:

```
for i = 1:m,
   Perform forward propagation and backpropagation using example (x(i),y(i))
   (Get activations a(l) and delta terms d(l) for l = 2,...,L
```

## Implementation

In [1]:
import numpy as np

In [2]:
theta1 = np.ones([10,11])
theta2 = 2*(np.ones([10,11]))
theta3 = 3*(np.ones([1,11]))

In [3]:
theta1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
theta2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [5]:
theta3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [6]:
thetaVec = np.array([theta1, theta2, theta3], dtype=object)

In [7]:
count = 0
for i in thetaVec:
    for j in i:
        count += len(j)
        
print("Number of elements in array:", count)

Number of elements in array: 231


In [8]:
thetaVec

array([array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
       array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
              [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
              [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
              [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
              [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
              [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
              [2., 2., 2., 2., 2., 2.,

In [9]:
((1+0.01)**3-(1-0.01)**3)/(2*0.01)

3.0001000000000055

In [11]:
j = 3*1 +2
((j+0.01)**3-(j-0.01)**3)/(2*0.01)

75.00009999999904